### ISSUE TITLE
A lot of sql query with MenuCRUD

### ISSUE THREAD

**Issue by evenloooo** [Laravel-Backpack/MenuCRUD#11]
Hi guys,
I found a issue with MenuCRUD. When I access CRUD admin page, the MenuCRUD make CRUD page loading slowly. 
Btw, I'm in the 'general' CRUD page.( not in the MenuCRUD page)
![image](https://cloud.githubusercontent.com/assets/9351031/19887525/d83aba00-a063-11e6-9110-a53b1d5ab5e5.png)
![image](https://cloud.githubusercontent.com/assets/9351031/19887989/d527fe6a-a066-11e6-9ab7-4f34abcb7604.png)

I added some code to speed up the page, but I think it's not a best way.
![image](https://cloud.githubusercontent.com/assets/9351031/19887782/7b8c98f8-a065-11e6-8f53-d4bbc35fffd2.png)
![image](https://cloud.githubusercontent.com/assets/9351031/19887972/b95b3328-a066-11e6-8ae0-954a9bbdd765.png)

Do you have some idea for fix this?
Thanks!

**Comment by tabacitu** [comment]
Hi @evenloooo ,

The getTree() function only does one select, so I don't think the problem is in the ViewComposer, but in the view itself (or in the layout view). I think you may be loading the menu view in a loop.

Cheers! 

PS. For development questions (non-bugs), it's recommended that you post on [Stack Overflow](http://stackoverflow.com/questions/tagged/backpack-for-laravel) (using the ```backpack-for-laravel``` tag) or [Gitter](https://gitter.im/BackpackForLaravel/Lobby), after you're sure you can't solve the problem yourself and there isn't an answer to that already. There are a lot more people on Gitter and StackOverflow. Plus:
- on StackOverflow people are rewarded with points for helping you out; 
- on StackOverflow your conversation will be better indexed by search engines;
- for super-urgent issues, nothing beats a chatroom, like Gitter; if anyone's online, of course;
- we can keep the Github Issues only for bugs that affect everyone, so we can crush them faster;

If you want to help people out with development question, that would be a [HUGE](https://i.imgflip.com/yuegp.jpg) help for the project. You can answer people:
- synchronously - by leaving your [Gitter app](https://gitter.im/apps) open;
- asynchronously - by [adding a StackOverflow filter](https://stackexchange.com/filters) for the ```backpack-for-laravel``` tag to receive questions by email;

Answering questions improves communication skills, makes you better understand the inner workings and improves your self-esteem. Just sayin' :-)
