### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by qeifar** [Laravel-Backpack/MenuCRUD#27]
Hi, I am confused on this tools. Can anyone guide me what need to do after installed it> No, I can create the menu and can order it, but there's no menu appear in sidebar or menu. Please help me.

**Comment by qeifar** [comment]
This is the picture
![aaaa](https://cloud.githubusercontent.com/assets/13729734/25559995/d04186cc-2d7a-11e7-98c8-9fe6db36e814.PNG)

**Comment by tabacitu** [comment]
Hi @qeifar ,

Backpack is just a tool for creating and updating stuff in the database. The MenuCRUD extension does that for a menu that you can use **on the front-end of your application**. Not your backend (admin panel). 

In order to see the menu items, you need to code that yourself. Here's [a quick snippet that might help you get started on that](https://github.com/Laravel-Backpack/MenuCRUD/issues/3#issuecomment-232072959).

Hope it helps. Cheers!

**Comment by qeifar** [comment]
Thank you @tabacitu
