### ISSUE TITLE
Menu Zones

### ISSUE THREAD

**Issue by imcodingideas** [Laravel-Backpack/MenuCRUD#28]
Do we have the way to have menu zones? For example: 

Top Menu
Footer Menu
Mobile Menu
Overflow Menu

You can see: https://demo.paintedbyawesome.com has a hamburger menu with a lot of menu items.

**Comment by lloy0076** [comment]
I don't think there is such a thing.

```
    /**
     * Get all menu items, in a hierarchical collection.
     * Only supports 2 levels of indentation.
     */
```

**Comment by tabacitu** [comment]
Hi @imcodingideas ,

MenuCRUD doesn't have that yet, no. @AbbyJanke 's PR does exactly that (see https://github.com/Laravel-Backpack/MenuCRUD/pull/23), but since it's a "breaking change", we need to bundle it with other breaking changes, so can't merge it just yet.

If you need it right now, I suggest install MenuCRUD "a la carte" (all controllers, requests, models your own project), and use her code.

Cheers!
