### ISSUE TITLE
Cannot order nested menus (3 deep)

### ISSUE THREAD

**Issue by scottgrayson** [Laravel-Backpack/MenuCRUD#38]
the hierarchy of my menu items goes

- navbar (no parent)
  - navbar children
  - `availabilities` (parent: navbar)  *trying to move this one
     - has children *and these
  - more navbar children

I can move all of the `navbar` children except for `availabilities` and children of `availabilities`

hopefully this video works.... http://recordit.co/RarLknM2tc
![image](https://user-images.githubusercontent.com/7796074/32137004-09d05ca2-bbe6-11e7-93a8-21f06f491af9.png)

**Comment by tabacitu** [comment]
Hi @scottgrayson - huh, I guess the pale red area isn't a very informative error... who would have thought? :-))

I bet your problem is that you only have one level of hierarchy activated in your MenuCRUD. In the [reorder docs](https://laravel-backpack.readme.io/docs/advanced-features#section-reordering-and-nesting-items) it specifies the code to enable the reordering of an entity:
```
$this->crud->enableReorder('label_name', MAX_TREE_LEVEL);
$this->crud->allowAccess('reorder');
```

You see, that MAX_TREE_LEVEL parameter lets CRUD know how many levels deep you would like to let your users nest items. I bet yours is set at ```1```, and that would be the normal behaviour, what I see in your video - letting the user nest 1 level deep, but no deeper. If you set it at ```0``` then it will be infinite. If you set it at ```2``` it will let him go 3 levels deep. Etc.

Was this it? Does changing that second parameter fix it for you?

Cheers!
