### ISSUE TITLE
class CRUD not found in menucrud.php line 18

### ISSUE THREAD

**Issue by JadJabbour** [Laravel-Backpack/MenuCRUD#40]
# Bug report
I saw that backpack settings and backpack permissions manager had the same issue any resolution?

**Comment by de-raaf-media** [comment]
Just had the same issue when updating to Laravel 5.5. Add this to the aliases in config/app.php:
 
'CRUD' => Backpack\CRUD\CrudServiceProvider::class,

**Comment by tabacitu** [comment]
Huh, that's weird. The alias is actually registered in CrudServiceProvider::register() so this shouldn't be a problem... Thanks for posting the workaround @de-raaf-media .

This _might_ have happened because of Laravel 5.5's package autodiscovery feature (some packages are sometimes discovered before others - in your case MenuCRUD might have been discovered before CRUD for some reason). In the hopes that this was it, I've switched the alias registering to autodiscovery too. Here's the commit on the CRUD dev branch - should be available publicly later this week, after some more testing - https://github.com/Laravel-Backpack/CRUD/commit/0973657a9bd3ac49f302ee69be0c6f5252e3d808

Thanks. Cheers!
