### ISSUE TITLE
Base/helpers functions return null

### ISSUE THREAD

**Issue by kpapag** [Laravel-Backpack/MenuCRUD#52]
# Bug report

### What I did:

Installed MenuCRUD and extended it from my custom class

### What I expected to happen:

To be able to use helpers functions like backpack_user(), etc

### What happened:

helpers functions keep returning null

### What I've already tried to fix it:

Also tried editing the derived files and use stock MenuCRUD, in case my extension messed this up, but it still does not work

**Comment by kpapag** [comment]
Ok so the problem seems to be that the latest versions of MenuCRUD (also applies to NewsCRUD) for Backpack 3.6 use crudcontrollers that do not initialize the public function setup(). public function __construct() seems to be used so im guessing thats the issue. Can someone confirm? Also will there be any fixes for these packages or support moved to backpack v4?

Thanks

**Comment by tabacitu** [comment]
Hi @kpapag ,

Sorry to hear you're having issue. Indeed - we're only pushing fixes for the Backpack v4 version at this moment. 

However, if you've already extended the MenuItemCrudController, and the problem is that ```_construct()``` is used instead of ```setup()```, you should be able to use ```setup()``` in your extended controller. I doubt that's the problem though - the helpers are loaded by Laravel, if Backpack\Base is installed. So they should be available inside any .php file that Laravel loads. At least that's how I see it.

Personally, I never use MenuCRUD and NewsCRUD as installed packages (and extending the classes in the package). I just copy-paste the code to my project and modify as needed. I think it works A LOT better that way, since they provide very simple functionality, and every project needs something different in terms of menus/blog.

Cheers!

**Comment by kpapag** [comment]
Hey @tabacitu 

Okay so i just tested it and indeed it was the use of _construct() that did not load the helpers function. When i used the setup() i was able to use the helpers functions again. Weird?

I'm writing this so if anyone has the same problem can fix this. 

Thanks
