### ISSUE TITLE
[Feature Proposal] Include menu ordering directly in the menu administration

### ISSUE THREAD

**Issue by SiL3NC3** [Laravel-Backpack/MenuCRUD#70]
# Feature Proposal

### What's the feature you think Backpack should have?

The order of the menu is not represented in the list of menu items of MenuCRUD add-on.
It would more admin-friendly if the order is directly shown and could be tweaked right there.
Also a good thing will be, to show the admin, that there are unsaved changed visually, like having a grayed out save button, when there is nothing changed, but activating it (with a tiny message), when there are unsaved changes detected.
Probably a general advise to have a generic implementation for this to use it in other add-ons as well.

### Have you already implemented a prototype solution, for your own project?

no

### Do you see this as a core feature or an add-on?

adjustments to Add-on > MenuCRUD

**Comment by SiL3NC3** [comment]
needs-more-info - What else should I provide?
I think the situation is clear... ;)

**Comment by tabacitu** [comment]
Everything's clear @SiL3NC3 😀  Robots make mistakes. Please note that I'm moving this to the icebox. While I think it's a good idea, I don't think we can dedicate the time to do this in the next few months. But I can't really close it because... as I said... I think it's a good idea.

Cheers!

**Comment by tabacitu** [comment]
I've decided MenuCRUD will not be receiving any more features. It's really wasn't meant to introduce any new UIs, just to provide a quick way to edit menu items... so... let's leave it like it is. If... in the future... we or someone else creates an Operation that makes sense to be used as the first-page for Menus, instead of the ListOperation, we'll use it.
