### ISSUE TITLE
page_or_link not available on Backpack 5

### ISSUE THREAD

**Issue by imtiazmahbub** [Laravel-Backpack/MenuCRUD#74]
# Bug report
Cannot find 'page_or_link' field view in any of the regular locations.
When trying for the URL: `/menu-item/create`

### What I did:
Installed backpack 5, PageManager, MenuCRUD with Pro Add-on
Followed setup instruction `(A) Download and place files in your application (recommended)`

### What I expected to happen:
Expected a field which implements: https://backpackforlaravel.com/docs/4.1/crud-fields#page_or_link

### What happened:
Got an error that says: `Cannot find 'page_or_link' field view in any of the regular locations.`

Checked the code `App\Http\Controllers\Admin\MenuItemCrudController`
```
            $this->crud->addField([
                'name' => ['type', 'link', 'page_id'],
                'label' => 'Type',
                'type' => 'page_or_link',
                'page_model' => '\Backpack\PageManager\app\Models\Page',
                'view_namespace' => file_exists(resource_path('views/vendor/backpack/crud/fields/page_or_link.blade.php')) ? null : 'menucrud::fields',
            ]);
```

Later found out that it's not available on Backpack 5 (latest at the moment)

### What I've already tried to fix it:
Removed the field. The create interface loads without problem.

### Backpack, Laravel, PHP, DB version:
Backpack 5, Laravel 9, PHP 8.1, MySQL: 8.0.28

**Comment by pxpm** [comment]
Hey @Rattone thanks for the report. 

I think the instructions are not 100% clear, we missed to add that you should also copy the `page_or_link.blade.php` file into your `resources/views/vendor/backpack/crud/fields` folder. 

This is now required because we moved the field from the main CRUD repository, so you need to copy it too when installing this manually. 

I've created the PR to add the instructions to the README! Will be closing this issue.

Thanks again for the report, wish you the best 🎅

**Comment by Rattone** [comment]
Hi @pxpm, I think you were wrong to tag me instead of @imtiazmahbub 😄

**Comment by pxpm** [comment]
> Hi @pxpm, I think you were wrong to tag me instead of @imtiazmahbub 😄

Totally!! 😅 Sorry @Rattone 🙏 

Wish you the best 🎅 🥂

**Comment by imtiazmahbub** [comment]
Thank you for the instructions. And also the mix-up in tagging. Got to chat with you both. 😄
